### ISSUE TITLE
Compile error: orphan instance

### ISSUE THREAD

**Issue by shybyte** [Thimoteus/purescript-simple-request#1]
Using the current purescript compiler 0.7.3.0 I get the following error:

```
Error at .../purescript-simple-request/src/Node/SimpleRequest/Foreign.purs line 25, column 1 - line 28, column 1:
  Instance foreignIsOption for Data.Options.IsOption Data.Foreign.Foreign is an orphan instance
See https://github.com/purescript/purescript/wiki/Error-Code-OrphanInstance for more information
```

I understand the reason described here https://github.com/purescript/purescript/wiki/Error-Code-OrphanInstance but I don't have enough experience in PureScript to find a simple solution.

**Comment by Thimoteus** [comment]
Yeah, the current version uses purescript-options which didn't provide an `IsOption Foreign` instance, so [I did it here](https://github.com/Thimoteus/purescript-simple-request/blob/master/src/Node/SimpleRequest/Foreign.purs#L25-L26) (though this implementation always made me feel uncomfortable). With 0.7.3+ orphan instances are disallowed, so I'll have to rethink how options should be sent. In the meantime you can use purescript-affjax, just remember to `npm install xmlhttprequest`.
