### ISSUE TITLE
Add this library to Pursuit?

### ISSUE THREAD

**Issue by paf31** [Thimoteus/purescript-simple-request#2]
It'd be nice to have this documented on [Pursuit](http://pursuit.purescript.org)

**Comment by Thimoteus** [comment]
[Fixed!](http://pursuit.purescript.org/packages/purescript-simple-request/2.0.1)

**Comment by paf31** [comment]
:+1: Thanks!

**Comment by pallix** [comment]
Can we reopen that? It's not in Pursuit anymore.
